### ISSUE TITLE
少数教材解析失败

### ISSUE THREAD

**Issue by happycola233** [happycola233/tchMaterial-parser#1]
**问题链接**：https://basic.smartedu.cn/tchMaterial/detail?contentType=assets_document&contentId=086004d9-8079-472c-8ab6-988f5e4fd40f&catalogType=tchMaterial&subCatalog=tchMaterial

**程序解析出的下载链接**：https://r2-ndr.ykt.cbern.com.cn/edu_product/esp/assets_document/086004d9-8079-472c-8ab6-988f5e4fd40f.pkg/pdf.pdf

使用[tchMaterial-parser](https://github.com/happycola233/tchMaterial-parser)解析并下载，会得到一个117 字节的无效pdf文件。

**Comment by happycola233** [comment]
您好，感谢您的反馈！

通过访问[api（web_config.json）](https://grey-config.ykt.cbern.com.cn/web_config.json)，有以下信息：
```
"host_private": "https://r1-ndr-private.ykt.cbern.com.cn,https://r2-ndr-private.ykt.cbern.com.cn,https://r3-ndr-private.ykt.cbern.com.cn",
"host_oversea": "https://r1-ndr-oversea.ykt.cbern.com.cn,https://r2-ndr-oversea.ykt.cbern.com.cn,https://r3-ndr-oversea.ykt.cbern.com.cn",
"host_public": "https://r1-ndr.ykt.cbern.com.cn,https://r2-ndr.ykt.cbern.com.cn,https://r3-ndr.ykt.cbern.com.cn"
```

**可以得知**：平台有**多个子域名**提供PDF下载服务


> **问题链接**：https://basic.smartedu.cn/tchMaterial/detail?contentType=assets_document&contentId=086004d9-8079-472c-8ab6-988f5e4fd40f&catalogType=tchMaterial&subCatalog=tchMaterial
> **程序解析出的下载链接**：https://r2-ndr.ykt.cbern.com.cn/edu_product/esp/assets_document/086004d9-8079-472c-8ab6-988f5e4fd40f.pkg/pdf.pdf

根据以上您提供的问题链接，使用浏览器F12可以获取到正确的PDF链接为：
https://r3-ndr.ykt.cbern.com.cn/edu_product/esp/assets/086004d9-8079-472c-8ab6-988f5e4fd40f.pkg/pdf.pdf
### 结论：程序使用固定的链接结构，不具普遍性


**通过分析**：
正确的PDF链接应从`https://s-file-1.ykt.cbern.com.cn/zxx/ndrv2/resources/tch_material/details/{contentId}.json`进行获取，应该下一个版本将会修复此问题

**Comment by wuziqian211** [comment]
已在 commit ce20b1d11edfcea2b9c38d8575468fb9ddca4b16 中修复
