### ISSUE TITLE
程序报错，官方把tag paths的接口改了

### ISSUE THREAD

**Issue by Doushabao233** [happycola233/tchMaterial-parser#11]
今天想下载课本，打开软件发现提示 网络连接异常，由于我是这个项目的贡献者，懂一点代码，于是下载了2.0版本的源代码文件，进行debug，最后发现问题在这行代码

![image](https://github.com/user-attachments/assets/2f092c1a-eece-44dc-ad6a-5797f04af302)

我翻了上面的代码，发现到这行代码的时候，他要爬取一个`tag_paths`里面的字符串，并且分割开，这个我猜最后会用在GUI界面底部选择“年级””几年级的上、下册“的下拉框中。但是现在获取到的数据里面全是一些随机的英文字母，不知道是哈希还是Base64。

![image](https://github.com/user-attachments/assets/4510b1bb-47dc-407b-b8d9-14d9cb61a84d)

![image](https://github.com/user-attachments/assets/0a86c306-19cd-4e1f-9613-b572979831c6)

幸运的是，旧版软件没有这个一键下载的功能，虽然麻烦，但是因为足够原始，所以这个程序依然可以打开，并且经过我的测试，旧版可以正常下载PDF，这更加印证了我前面说的”tag_paths代表的是书籍分门别类的关系，最后会显示在GUI底部“：

![image](https://github.com/user-attachments/assets/0e0ea67f-218b-40d6-a055-61ae62932f22)

这是我浅显的理解，不太准确，希望能确认一下并且修复

修复方法也很简单，可以不从网上爬层级顺序，可以硬编码在程序里，也可以解密一下这个加密的字符串，再不济可以直接砍了[doge]

**Comment by wuziqian211** [comment]
感谢您的反馈～

但是该问题出现的原因不是数据经过了加密，而是在获取资料的信息的时候，有些资料的 tag_paths 为空数组，这就导致您发的图 1 中的代码在获取 i["tag_paths"][0] 时由于索引超出范围而报错😂

该问题将在 v2.1 版本中修复。
