### ISSUE TITLE
英语音频材料下载

### ISSUE THREAD

**Issue by mrguangtu** [happycola233/tchMaterial-parser#15]
https://basic.smartedu.cn/tchMaterial/detail?contentType=assets_document&contentId=485d2118-1652-ea90-8da7-5b9eaeb71dc4&catalogType=tchMaterial&subCatalog=tchMaterial

![image](https://github.com/user-attachments/assets/b13e2ef6-6397-4192-80eb-9ab523860b15)
这里面有不少英语听力，是否可以一并下载？

**Comment by wuziqian211** [comment]
您好，目前本程序暂时没有这个功能，可能后面的版本会添加😂

**Comment by momolibrary** [comment]
尝试增加了这个功能。
