### ISSUE TITLE
能否增添支持对"基础性作业"的下载

### ISSUE THREAD

**Issue by iamzhz** [happycola233/tchMaterial-parser#9]
能否增添支持对形如`https://basic.smartedu.cn/syncClassroom/basicWork/detail?contentType=assets_document&contentId=87ae8939-4de5-4413-9c96-de189bc14ddc&catalogType=basicWork`的"基础性作业"的下载.  
  
 
> 一个貌似可行的方案：
原链接为`https://basic.smartedu.cn/syncClassroom/basicWork/detail?contentType=assets_document&contentId=<CONTENTID>&catalogType=basicWork`的形式 ，
则其PDF地址为`https://r1-ndr.ykt.cbern.com.cn/edu_product/esp/assets/<CONTENTID>.pkg/<科目>作业.%20<年级>年级%20<上或下>册.pdf`

emmm，一个貌似更加可行的方案，不需要爬取除contentId外的其他信息  

由原URL类似于：`https://basic.smartedu.cn/syncClassroom/basicWork/detail?contentType=assets_document&contentId=XXXXXXXXXXX&catalogType=basicWork`  
中间的XXX暂且称为contentId  

可以由contentId直接得到一个json文件：
`https://s-file-1.ykt.cbern.com.cn/zxx/ndrs/special_edu/resources/details/XXXXXXXX.json`
把它当成字典(们)，那么这之中的`["ti_items"][1]["ti_storages"][0]`就是pdf的url

**Comment by lwkin** [comment]
大神门，能详细指导一下嘛，我按照你提出的这个解析不了

**Comment by iamzhz** [comment]
emmm，一个貌似更加可行的方案，不需要爬取除contentId外的其他信息  

由原URL类似于：`https://basic.smartedu.cn/syncClassroom/basicWork/detail?contentType=assets_document&contentId=XXXXXXXXXXX&catalogType=basicWork`  
中间的XXX暂且称为contentId  

可以由contentId直接得到一个json文件：
`https://s-file-1.ykt.cbern.com.cn/zxx/ndrs/special_edu/resources/details/XXXXXXXX.json`
把它当成字典(们)，那么这之中的`["ti_items"][1]["ti_storages"][0]`就是pdf的url
